version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - frontend-network
      - devops-network

networks:
  frontend-network:
    driver: bridge
  devops-network:
    external: true
